version: '3.8'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:6.2.0
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
      image: confluentinc/cp-kafka:6.2.0
      hostname: broker
      container_name: broker
      depends_on:
        - zookeeper
      ports:
        - "9092:9092"
      environment:
        KAFKA_BROKER_ID: 1
        KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
        KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092,PLAINTEXT_HOST://localhost:29092
        KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
        KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
        KAFKA_TOOLS_LOG4J_LOGLEVEL: ERROR
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
  jms:
    image: rabbitmq:management-alpine
    ports:
      - 5672:5672
      - 15672:15672
  eureka:
    image: prcompany/atlantico-discovery-server
    ports:
      - 8761:8761
  config:
    image: prcompany/atlantico-config-server
    ports:
      - 8888:8888
    depends_on:
      - eureka
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://netflix:eureka@eureka:8761/eureka
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: 'true'
  db:
    image: postgres:11.12-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password
  user-api:
    image: prcompany/atlantico-user-api
    ports:
      - 8080:8080
    depends_on:
      - jms
      - db
      - redis
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: reunion
      DB_USER: postgres
      DB_PASSWORD: password
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://netflix:eureka@eureka:8761/eureka
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: 'true'
      RABBITMQ_HOST: jms
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: guest
      RABBITMQ_PASSWORD: guest
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ''
    restart: on-failure
  kafka-bus:
    image: prcompany/atlantico-kafka-bus
    ports:
      - 8081:8081
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SEVER_PORT: 8081
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://netflix:eureka@eureka:8761/eureka
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: 'true'
      RABBITMQ_HOST: jms
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: guest
      RABBITMQ_PASSWORD: guest
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ''
      KAFKA_BROKERS: broker:9092
    restart: on-failure
