version: '3.8'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.1
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
  kibana:
      image: docker.elastic.co/kibana/kibana:7.12.1
      ports:
        - 5601:5601
      restart: on-failure
      depends_on:
        - elasticsearch
  filebeat:
      image: docker.elastic.co/beats/filebeat:7.12.1
      command: filebeat -e -strict.perms=false
      volumes:
        - ./filebeat/filebeat.docker.yml:/usr/share/filebeat/filebeat.yml:ro # Configuration file
        - /var/lib/docker/containers:/var/lib/docker/containers:ro           # Docker logs
        - /var/run/docker.sock:/var/run/docker.sock:ro                       # Additional information about containers
      user: root
      restart: on-failure
  zookeeper:
    image: confluentinc/cp-zookeeper:6.2.0
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
      image: confluentinc/cp-kafka:6.2.0
      hostname: broker
      container_name: broker
      depends_on:
        - zookeeper
      ports:
        - "9092:9092"
      environment:
        KAFKA_BROKER_ID: 1
        KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
        KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092,PLAINTEXT_HOST://localhost:29092
        KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
        KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
        KAFKA_TOOLS_LOG4J_LOGLEVEL: ERROR
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
  jms:
    image: rabbitmq:management-alpine
    ports:
      - 5672:5672
      - 15672:15672
  eureka:
    image: prcompany/atlantico-discovery-server
    ports:
      - 8761:8761
  zipkin:
    image: openzipkin/zipkin
    ports:
      - 9411:9411
  config:
    image: prcompany/atlantico-config-server
    ports:
      - 8888:8888
    depends_on:
      - eureka
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://netflix:eureka@eureka:8761/eureka
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: 'true'
  user-api:
    image: prcompany/atlantico-user-api
    ports:
      - 8080:8080
    depends_on:
      - jms
      - redis
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DB_URL: jdbc:h2:mem:testdb
      DB_DRIVER_CLASS: org.h2.Driver
      DB_PLATFORM: org.hibernate.dialect.H2Dialect
      DB_USER: sa
      DB_PASSWORD: ''
      SPRING_H2_CONSOLE_ENABLED: 'true'
      SPRING_H2_CONSOLE_PATH: '/h2-console'
      SPRING_H2_CONSOLE_SETTINGS_WEB-ALLOW-OTHERS: 'true'
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://netflix:eureka@eureka:8761/eureka
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: 'true'
      RABBITMQ_HOST: jms
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: guest
      RABBITMQ_PASSWORD: guest
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ''
      ZIPKIN_HOST: zipkin
      ZIPKIN_PORT: 9411
    restart: on-failure
    labels:
      collect_logs_with_filebeat: "true"
      decode_log_event_to_json_object: "true"
  kafka-bus:
    image: prcompany/atlantico-kafka-bus
    ports:
      - 8081:8081
    depends_on:
      - jms
      - redis
      - user-api
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SEVER_PORT: 8081
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://netflix:eureka@eureka:8761/eureka
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: 'true'
      RABBITMQ_HOST: jms
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: guest
      RABBITMQ_PASSWORD: guest
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ''
      KAFKA_BROKERS: broker:9092
      ZIPKIN_HOST: zipkin
      ZIPKIN_PORT: 9411
    restart: on-failure
    labels:
      collect_logs_with_filebeat: "true"
      decode_log_event_to_json_object: "true"
